services:
  postgres:
    image: postgres:13.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-test}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      - basicduo_develop
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
networks:
  basicduo_develop:
    external: true
