services:
  events-api-develop:
    build:
      context: "."
    restart: always
    container_name: events-api-develop
    working_dir: /opt/basicduo
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8080 --workers 1
    ports:
      - 9119:8080
    networks:
      - seen_develop
    environment:
      DEBUG: 1
      POSTGRES_DB_PASSWORD: changeme
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_HOST: "postgres_container"
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_SCHEMA: eventsapp
    volumes:
      - ./app:/opt/basicduo/app
      - ./tests:/opt/basicduo/tests
      - ./alembic:/opt/basicduo/alembic
networks:
  seen_develop:
    external: true
